development:
  adapter: postgresql
  encoding: unicode
  database: saas_app_development
  host: localhost
  pool: 5
  username: <username>
  password: <password>

test:
  adapter: postgresql
  encoding: unicode
  database: saas_app_test
  host: localhost
  pool: 5
  username: <username>
  password: <password>

production:
  adapter: postgresql
  encoding: unicode
  database: syook_app_production
  host: localhost
  pool: 5
  username: <username>
  password: <password>
